/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AOption: typeof import('@arco-design/web-vue')['Option']
    AOptions: typeof import('@arco-design/web-vue')['Options']
    APopover: typeof import('@arco-design/web-vue')['Popover']
    APropver: typeof import('@arco-design/web-vue')['Propver']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    Grid: typeof import('./src/components/grid/grid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    XColorInput: typeof import('./src/components/x-color-picker/components/x-color-input/x-color-input.vue')['default']
    XColorPicker: typeof import('./src/components/x-color-picker/x-color-picker.vue')['default']
    XGrid: typeof import('./src/components/grid/x-grid.vue')['default']
    XSlider: typeof import('./src/components/x-slider.vue')['default']
  }
}
